### ISSUE TITLE
Orientation field shows up in all platforms

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/displays-app#26]
Steps to reproduce:
1. Go to https://displays.risevision.com/
2. Click on a display that is *not* running Chrome OS.

Result:
Orientation selector is visible.

How it should work:
Orientation selector should not be visible.

Link to Presentation:
N/A

OS:
Xubuntu 14.04

Chrome Ver:
Version 41.0.2272.118 (64-bit)

--------------------

Additional information:

Display is running CAP QA 1.24.28 installed from 
https://chrome.google.com/webstore/detail/rise-vision-chrome-app-pl/beflgpmcfpdkkjjcbhdmkdnjgeaehcdg

Player is configured to use:
http://1-06-038.rvashow2.appspot.com/

(these are confirmed in displays.risevision.com)

**Comment by ByronDarlison** [comment]
@alex-deaconu is this issue now closed? Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison Yes it is. Will close. Thanks.
