### ISSUE TITLE
Display status indicator (in display list page) does not correctly reflect status

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/displays-app#29]
* this involves the testing version of the displays app *

Steps to reproduce:
1. Go to https://displays-stage-0.risevision.com/
2. Look for a display known to be online (switching to a sub-company if necessary)

Result:
Status indicator is grey (presumably indicating offline or not registered)?

How it should work:
Behavior in current version is that there is a green indicator, signifying that the display is online.

Link to Presentation:
N/A

OS:
Xubuntu 14.04.2

Chrome Ver:
Version 41.0.2272.118 (64-bit)

**Comment by rodrigopavezi** [comment]
@mfisher11 could you check if the same is happening on https://displays-stage-1.risevision.com/? If that is the case this issue was already there and could not be introduced by the common-header upgrade. cheers

**Comment by mfisher11** [comment]
@rodrigopavezi Yep.  Unrelated to the common-header upgrade.  Thanks!

**Comment by alex-deaconu** [comment]
@mfisher11 @rodrigopavezi this issue is related to some Core changes that have yet to be released to production. There's a PR for this https://github.com/Rise-Vision/displays-app/pull/23. Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu @rodrigopavezi is this issue closed? Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison I believe this is fixed, in the Core and in the App. @rodrigopavezi can you confirm? Thanks.

**Comment by rodrigopavezi** [comment]
@ByronDarlison @alex-deaconu I believe it was fixed as well. We implemented that task for indexing it then it was recently removed as the status now relies only on the channel connection status. @mfisher11 could you please verify? cheers

**Comment by mfisher11** [comment]
@rodrigopavezi Should I be checking this in displays-stage-0 and displays-stage-1?
I've confirmed that it is working in displays.risevision.com.

**Comment by rodrigopavezi** [comment]
@mfisher11 checking on displays.risevision.com is enough. It was a backend change on core so all the client apps would be affected and it has been fixed for a good while. I will close this issue. cheers
