### ISSUE TITLE
Chrome OS - when set to portrait rotation, half of the content is cutoff/white

### ISSUE THREAD

**Issue by justinsmith1** [Rise-Vision/displays-app#57]
Steps to reproduce:

1. Assign a portrait presentation to a ChromeOS device.
2. Go to displays.risevision.com and set the ChromeOS device to portrait rotation.

Result:
Player rotates to portrait orientation, but half of the content is cutoff/white.
Picture: http://screencast.com/t/N4qaybZUFEBI

How it should work:
Player should display full presentation in portrait orientation. 

Link to Presentation:
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=aae9e033-4fa8-4915-ad20-42c13e748438?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Chrome OS 

Chrome Ver:
44.0.2403.44

**Comment by ByronDarlison** [comment]
@alex-deaconu @mfarooq2000 can you review this defect and let me know where you think the problem is and who should fix it?

@tejohnso @fjvallarino you should follow the problem as we need to make sure that the offline player doesn't have the same issue.

Thanks

**Comment by mfarooq2000** [comment]
@ByronDarlison The problem would be in the Chrome Player. I will be working on this issue. Thanks
fyi @alex-deaconu

**Comment by btfrise** [comment]
@mfarooq2000 I have set up a card for this at https://trello.com/c/ZQSNLbMc can you please keep me up to date with your findings? Thanks.

**Comment by ByronDarlison** [comment]
Thanks @mfarooq2000

**Comment by ByronDarlison** [comment]
@mfarooq2000 @btfrise @justinsmith1 could you confirm if this is still open? Thanks

**Comment by mfarooq2000** [comment]
@ByronDarlison It was fixed, will wait for @btfrise @justinsmith1 to confirm. Thanks

**Comment by ByronDarlison** [comment]
Thanks @mfarooq2000

**Comment by ByronDarlison** [comment]
@btfrise @justinsmith1 is this fix confirmed?

**Comment by btfrise** [comment]
@ByronDarlison @justinsmith1 This fix is confirmed.
