### ISSUE TITLE
Displays app will not show sub-company assets.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/displays-app#93]
Steps to replicate
1. Access displays.risevision.com
2. Select a sub-company

What I expected to happen
Once the sub-company is selected, it should show displays from that sub company.

What actually happens
Displays from the parent company still show.

http://www.screencast.com/t/m3oy3xaF6

**Comment by ezequielc** [comment]
@btfrise This is fixed. Would you like to check? Thanks!

**Comment by robb-price** [comment]
@ezequielc @btfrise Verified and Closed.

Thanks!
