### ISSUE TITLE
Updating the Timezone for a Display does not save

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/displays-app#94]
<b>How it works now:</b>
1. Add a Display or use an existing one at apps.risevision.com/displays.
2. Deselect Use Company Address, and enter a custom address, including a custom time zone.
3. Once you press Save, all your information appears to save, but when you leave that page and come back to it, all the custom address info is saved, but the timezone has not been saved.

<b>How I expect it to work:</b>
All information, including the timezone should be saved when you set a custom address.

**Comment by lapinnoir** [comment]
Intercom conversation https://app.intercom.io/a/apps/d85f4ah4/inbox/ray.durkin@risevision.com/conversations/1583254399

**Comment by lapinnoir** [comment]
Intercome conversation https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1583254399

**Comment by ByronDarlison** [comment]
@ezequielc @alex-deaconu what's the plan for this one? Thanks

**Comment by ezequielc** [comment]
@ByronDarlison we are going to use one point from our buffer. I will add a card for it. Thanks

**Comment by ByronDarlison** [comment]
Thanks @ezequielc

**Comment by ezequielc** [comment]
@robb-price @lapinnoir I just released a fix for the issue. Would you like to check? Thanks!

**Comment by robb-price** [comment]
Verified and Closed. User has been notified in Intercom.
