### ISSUE TITLE
User gets booted back to master company after clicking "Save" on Display page.

### ISSUE THREAD

**Issue by ashleighalmeida** [Rise-Vision/displays-app#97]
What is happening:

The user switches to their sub company
User navigates into their display's page and clicks save. 
Once they click the "Displays" link to go back to their master list, they are brought back to the parent company.

What should be happening:
When user clicks "Save" on the display page, they are brought back to their master list inside of being bounced back to the parent company.

Recreation Demo:
https://drive.google.com/a/risevision.com/file/d/0B5_6TQ6T_mw1UFlSNEMtZEJ2OWc/view?usp=sharing

Thanks!

**Comment by ashleighalmeida** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/apa@risevision.com/conversations/1845881254

**Comment by ezequielc** [comment]
@ashleighalmeida This project was merged into https://github.com/Rise-Vision/rise-vision-apps/ .
I will close the issue here and reopen in that repository.
Whenever you find an issue with Displays, Schedules or Editor, please add them to rise-vision-apps . 
Thanks!
